version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Restoring NuGet packages...
      - dotnet restore

  build:
    commands:
      - echo Building the solution...
      - dotnet build --configuration Release