<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702; CA1848;CS1573;CS1591 </NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CA1848</WarningsNotAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;CS1573;CS1591</NoWarn>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CA1848</WarningsNotAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1573</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="SeedData\ProductData.cs~RF44073381.TMP" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Answer.King.Domain\Answer.King.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Answer.King.Api.UnitTests" />
    <InternalsVisibleTo Include="$(AssemblyName).UnitTests" />
  </ItemGroup>

</Project>
