name: .NET Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
    - develop
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.102

      - name: Restore NuGet packages
        uses: dotnet/actions@v1
        with:
          command: restore
          projects: '**/*.csproj'

      - name: Build all projects
        uses: dotnet/actions@v1
        with:
          command: build
          projects: '**/*.csproj'

      - name: Run tests
        uses: dotnet/actions@v1
        with:
          command: test
          arguments: --no-build
          projects: 'src/tests/*.csproj'

